default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: docket_donkey

test:
  <<: *default
  database: docket_donkey

production:
  <<: *default
  database: docket_donkey
